### ISSUE TITLE
Possible NOOB issue

### ISSUE THREAD

**Issue by jcabbott86** [s0meguy1/RougeWifi#1]
i moved all files to dir listed. 

when typing this command 

root@anonymous:~# www-data ALL=(ALL:ALL) NOPASSWD: /sbin/iptables, /usr/sbin/arpbash: syntax error near unexpected token `('
 i get a syntax error. am i doing something wrong? 
please help

**Comment by Z-slim** [comment]
That line needs to be added to the /etc/sudoers file, not typed into the prompt. Good practice to modify the sudoers file using visudo from a terminal. ie. root@anonymous:~# visudo

Typing the command on it's own will automatically open the sudoers file for editing (sort of) with some safety/sanity checks to avoid damaging the ability for users to sudo.
It is a nano like interface inside the terminal, but requires different keys for operation. 

Use the arrow keys to move cursor down to underneath root ALL(ALL:ALL) line and press Insert on your keyboard to enable actual editing (will say --Insert-- in lower left of window). Type in the www-data line as given in the readme. Now, press Ctrl+c. This will not exit visudo, but only exit editing mode. Now type :w and press enter to write your changes to file and have it parsed for errors. Assuming no errors, type :q and press enter to quit visudo.  If you messed up somewhere, type :qa! and press enter to discard any changes and exit, then try again. Nnote that commands are preceded by a colon : which interprets your next keystrokes as editor commands.

Worth a mention that you should pay attention to Apache DocumentRoot. If it is other than the default /var/www/html/ you'll need to either reset it or change the directory you place the files into to the one listed as DocumentRoot in your Apache setup otherwise this likely will not work (had this issue myself). How to do this is beyond the scope of your immediate needs and google will be your friend..

**Comment by zeeshan7860** [comment]
Not working Rogue wifi....i have placed all the files in html folder and run the command www-data:www-data ./*.................it says www-data bash not found something like that

**Comment by s0meguy1** [comment]
Closing, not maintaining this anymore
