### ISSUE TITLE
Captive portal not  opens after connecting to Access Point why Done all the steps mentioned in Read me file

### ISSUE THREAD

**Issue by krithick14** [s0meguy1/RougeWifi#5]

**Comment by s0meguy1** [comment]
Can you provide some logs? Also could you open the dev console in your browser before you browse to it, then browse to it and paste the results? As I said on Twitter, I'll look later, but this info will help me understand

**Comment by krithick14** [comment]
cant understand

**Comment by s0meguy1** [comment]
Hey I wrote this years ago as a simple PoC for how to further social engineer people to authenticate to a wifi portal. Every time I look at the code I wrote, I cringe, and I really do not feel like re-writing it or continuing to maintain it. Someone else has taken my code and really done cool stuff with it. I highly recommend you use this guys tool, its my code, but way, way better:
https://github.com/vincenzogianfelice/RoguePortal

**Comment by krithick14** [comment]
Bro i need it in english language

**Comment by s0meguy1** [comment]
If you are asking me to translate for you, I am sorry, I can't do that. Otherwise I am going to close this out. I recommend using his tool, despite the language barrier as it has much more functionality. You are welcome to fork my tool and develop it in any direction you would like to go. In any case, I am going to close this ticket
